---
output: html_document
---

```{r setup, include=FALSE}
# R-Markdown Options
knitr::opts_chunk$set(echo = FALSE, cache = TRUE)
# Dependencies
library(data.table)
library(ggplot2)
dodge <- position_dodge(width = 0.9)
```

```{r variables, include=FALSE}
scale_smape <- 70
scale_mase <- 4
scale_smis <- 12

gg_violin_theme <- theme(
  plot.background = element_rect(fill = NA), 
  panel.background = element_rect(fill = NA),
  panel.border = element_blank(),
  panel.grid.major = element_line(colour = "lightgrey"), 
  panel.grid.major.y = element_blank(),
  legend.title = element_blank(), 
  legend.position = "bottom",
  legend.key = element_blank(),
  panel.spacing = unit(0.5, "lines"),
  axis.title.y = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks.y = element_blank()
)
gg_stackbar_theme <- theme(
  plot.background = element_rect(fill = NA),
  panel.background = element_rect(fill = NA),
  panel.border = element_blank(),
  panel.grid.major = element_blank(),
  axis.ticks.y = element_blank(),
  legend.position = "bottom",
  legend.key = element_blank(),
  panel.spacing = unit(0.5, "lines")
)
```

```{r data, include=FALSE}
# Read Data
acc_ebit_h1 <- readRDS("../acc_ebit_h1.rds")

acc_ebit_melt <- data.table::melt(
  acc_ebit_h1,
  id.vars = c("company", "type", "h"),
  measure.vars = c("smape", "mase", "smis"),
  variable.name = "metric",
  value.name = "accuracy"
)
acc_ebit_melt[, metric := factor(
  metric,
  levels = c("smape", "mase", "smis"),
  labels = c("sMAPE", "MASE", "sMIS")
)]
acc_ebit_melt[, type := factor(type, levels = rev(unique(type)))]

# EBIT (rank)
acc_ebit_rank_melt <- data.table::melt(
  acc_ebit_h1,
  id.vars = c("company", "type", "h"),
  measure.vars = c("rank_smape", "rank_mase", "rank_smis"),
  variable.name = "metric",
  value.name = "rank"
)
acc_ebit_rank_melt[, metric := factor(
  metric,
  levels = c("rank_smape", "rank_mase", "rank_smis"),
  labels = c("sMAPE (rk)", "MASE (rk)", "sMIS (rk)")
)]
acc_ebit_rank_melt[, type := factor(type, levels = rev(unique(type)))]
```

### (i) H1: Accuracy Naive + SNaive + Drift + Holt + ARIMA

#### Original
```{r accuracy, fig.height = 10}
ggplot(acc_ebit_melt, aes(x = accuracy, y = type)) +
  geom_violin(aes(group=interaction(type, h)), position = dodge) +
  geom_boxplot(aes(fill = type), width = 0.18, outlier.shape = NA, position = dodge) +
  facet_grid(h ~ metric, scales = "free") +
  scale_fill_brewer(palette = "Set1") +
  xlab(NULL) + ylab(NULL) +
  guides(fill = guide_legend(nrow = 1, reverse = TRUE)) +
  gg_violin_theme
```

\newpage
#### Scaled
```{r accuracy_scaled, fig.height = 10}
ggplot(acc_ebit_melt[
  (metric == "sMAPE" & accuracy < scale_smape) | 
    (metric == "MASE" & accuracy < scale_mase) |
    (metric == "sMIS" & accuracy < scale_smis)
], aes(x = accuracy, y = type)) +
  geom_violin(aes(group=interaction(type, h)), position = dodge) +
  geom_boxplot(aes(fill = type), width = 0.18, outlier.shape = NA, position = dodge) +
  facet_grid(h ~ metric, scales = "free") +
  scale_fill_brewer(palette = "Set1") +
  xlab(NULL) + ylab(NULL) +
  guides(fill = guide_legend(nrow = 1, reverse = TRUE)) +
  gg_violin_theme
```

\newpage
### (ii) H1: Rank Naive + SNaive + Drift + Holt + ARIMA

#### Mean of Ranks per Split
```{r mean_rank, fig.height = 10}
acc_ebit_h1_rankavg <- readRDS("../acc_ebit_h1_rankavg.rds")
acc_ebit_h1_rankavg[, type := factor(type, levels = rev(unique(type)))]

ggplot(acc_ebit_h1_rankavg, aes(x = rank_mean, y = type)) +
  geom_violin(aes(group=interaction(type, h)), position = dodge) +
  geom_boxplot(aes(fill = type), width = 0.18, outlier.shape = NA, position = dodge) +
  facet_grid(h ~ metric, scales = "free") +
  scale_fill_brewer(palette = "Set1") +
  xlab(NULL) + ylab(NULL) +
  guides(fill = guide_legend(nrow = 1, reverse = TRUE)) +
  gg_violin_theme
```

\newpage
#### Stacked Ranks Baselines vs. ARIMA (only)
```{r rank_stack_01}
# Re-Factor rank and type for "correct" ordering
acc_ebit_rank_melt[, rank := factor(rank, levels = sort(unique(rank), decreasing = TRUE))]
acc_ebit_rank_melt[, type := factor(type, levels = rev(unique(type)))]

ggplot(
  data = acc_ebit_rank_melt,
  mapping = aes(y = type, fill = factor(rank))
) +
  geom_bar(position = "fill") +
  facet_grid(h ~ metric) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_fill_brewer(palette = "RdYlBu") +
  xlab(NULL) + ylab(NULL) + 
  guides(fill = guide_legend(title = "Rank", nrow = 1, reverse = TRUE)) +
  gg_stackbar_theme
```

#### Stacked Ranks Baselines vs. ARIMA (incl. Simple, GRU, LSTM, ARNN)
```{r rank_stack_02}
# Read Data
acc_ebit_01 <- readRDS("../acc_ebit_01.rds")

# EBIT (rank)
acc_ebit_01_rank_melt <- data.table::melt(
  acc_ebit_01,
  id.vars = c("company", "type", "h"),
  measure.vars = c("rank_smape", "rank_mase", "rank_smis"),
  variable.name = "metric",
  value.name = "rank"
)
acc_ebit_01_rank_melt[, metric := factor(
  metric,
  levels = c("rank_smape", "rank_mase", "rank_smis"),
  labels = c("sMAPE (rk)", "MASE (rk)", "sMIS (rk)")
)]
acc_ebit_01_rank_melt[, rank := factor(rank, levels = sort(unique(rank), decreasing = TRUE))]
acc_ebit_01_rank_melt[, type := factor(type, levels = rev(unique(type)))]

# Plot
ggplot(
  data = acc_ebit_01_rank_melt[type %in% c("Naive", "Snaive", "Drift", "Holt", "ARIMA")],
  mapping = aes(y = type, fill = factor(rank))
) +
  geom_bar(position = "fill") +
  facet_grid(h ~ metric) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_fill_brewer(palette = "RdYlBu") +
  xlab(NULL) + ylab(NULL) + 
  guides(fill = guide_legend(title = "Rank", nrow = 1, reverse = TRUE)) +
  gg_stackbar_theme
```
