---
  output: html_document
---

```{r setup, include=FALSE}
# R-Markdown Options
knitr::opts_chunk$set(echo = FALSE, cache = TRUE)
# Dependencies
library(data.table)
library(ggplot2)
```

```{r variables, include=FALSE}
gg_theme <- theme(
  plot.background = element_rect(fill = NA),
  panel.background = element_rect(fill = NA),
  panel.grid.major = element_blank(),
  panel.border = element_blank(),
  axis.ticks.y = element_blank(),
  legend.position = "bottom",
  legend.key = element_blank(),
  panel.spacing = unit(0.5, "lines")
)
```

```{r data_ebit, include=FALSE}
acc_rank_str <- c("smape", "mase")

# read data
acc_ebit <- readRDS("../acc_ebit.rds")

acc_ebit_split <- acc_ebit[
  , lapply(.SD, mean), by = c("ticker", "h", "type"), .SDcols = acc_rank_str]
acc_ebit_split[
  , paste0("avgrank_", acc_rank_str) := lapply(.SD, frank, ties.method = "min"),
  by = c("ticker", "h"),
  .SDcols = acc_rank_str
]
acc_ebit_split_rank_melt <- data.table::melt(
  acc_ebit_split,
  id.vars = c("ticker", "type", "h"),
  measure.vars = c("avgrank_smape", "avgrank_mase"),
  variable.name = "metric",
  value.name = "rank"
)
acc_ebit_split_rank_melt[, metric := factor(
  metric,
  levels = c("avgrank_smape", "avgrank_mase"),
  labels = c("sMAPE (rk)", "MASE (rk)")
)]
# Re-Factor rank and type for "correct" ordering
acc_ebit_split_rank_melt[, rank := factor(rank, levels = sort(unique(rank), decreasing = TRUE))]
acc_ebit_split_rank_melt[, type := factor(type, levels = rev(levels(type)))]
```

```{r data_ni, include=FALSE}
acc_rank_str <- c("smape", "mase")

# read data
acc_ni <- readRDS("../acc_ni.rds")

acc_ni_split <- acc_ni[
  , lapply(.SD, mean), by = c("ticker", "h", "type"), .SDcols = acc_rank_str]
acc_ni_split[
  , paste0("avgrank_", acc_rank_str) := lapply(.SD, frank, ties.method = "min"),
  by = c("ticker", "h"),
  .SDcols = acc_rank_str
]
acc_ni_split_rank_melt <- data.table::melt(
  acc_ni_split,
  id.vars = c("ticker", "type", "h"),
  measure.vars = c("avgrank_smape", "avgrank_mase"),
  variable.name = "metric",
  value.name = "rank"
)
acc_ni_split_rank_melt[, metric := factor(
  metric,
  levels = c("avgrank_smape", "avgrank_mase"),
  labels = c("sMAPE (rk)", "MASE (rk)")
)]
# Re-Factor rank and type for "correct" ordering
acc_ni_split_rank_melt[, rank := factor(rank, levels = sort(unique(rank), decreasing = TRUE))]
acc_ni_split_rank_melt[, type := factor(type, levels = rev(levels(type)))]
```

```{r data_eps, include=FALSE}
acc_rank_str <- c("smape", "mase")

# read data
acc_eps <- readRDS("../acc_eps.rds")

acc_eps_split <- acc_eps[
  , lapply(.SD, mean), by = c("ticker", "h", "type"), .SDcols = acc_rank_str]
acc_eps_split[
  , paste0("avgrank_", acc_rank_str) := lapply(.SD, frank, ties.method = "min"),
  by = c("ticker", "h"),
  .SDcols = acc_rank_str
]
acc_eps_split_rank_melt <- data.table::melt(
  acc_eps_split,
  id.vars = c("ticker", "type", "h"),
  measure.vars = c("avgrank_smape", "avgrank_mase"),
  variable.name = "metric",
  value.name = "rank"
)
acc_eps_split_rank_melt[, metric := factor(
  metric,
  levels = c("avgrank_smape", "avgrank_mase"),
  labels = c("sMAPE (rk)", "MASE (rk)")
)]
# Re-Factor rank and type for "correct" ordering
acc_eps_split_rank_melt[, rank := factor(rank, levels = sort(unique(rank), decreasing = TRUE))]
acc_eps_split_rank_melt[, type := factor(type, levels = rev(levels(type)))]
```

### Rank of each ticker (mean metric across splits)

#### EBIT
```{r stack_ebit}
ggplot(
  data = acc_ebit_split_rank_melt[type %in% c("ARIMA", "Simple", "GRU", "LSTM", "ARNN")], 
  mapping = aes(y = type, fill = rank)
) +
  geom_bar(position = "fill") +
  facet_grid(h ~ metric) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_fill_brewer(palette = "RdYlBu") +
  xlab(NULL) + ylab(NULL) + 
  guides(fill = guide_legend(title = "Rank", nrow = 1, reverse = TRUE)) +
  gg_theme
```

#### Net Income
```{r stack_ni}
ggplot(
  data = acc_ni_split_rank_melt[type %in% c("ARIMA", "Simple", "GRU", "LSTM", "ARNN")], 
  mapping = aes(y = type, fill = rank)
) +
  geom_bar(position = "fill") +
  facet_grid(h ~ metric) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_fill_brewer(palette = "RdYlBu") +
  xlab(NULL) + ylab(NULL) + 
  guides(fill = guide_legend(title = "Rank", nrow = 1, reverse = TRUE)) +
  gg_theme
```

#### EPS
```{r stack_eps}
ggplot(
  data = acc_eps_split_rank_melt[type %in% c("ARIMA", "Simple", "GRU", "LSTM", "ARNN")], 
  mapping = aes(y = type, fill = rank)
) +
  geom_bar(position = "fill") +
  facet_grid(h ~ metric) +
  scale_x_discrete(expand = c(0, 0)) +
  scale_fill_brewer(palette = "RdYlBu") +
  xlab(NULL) + ylab(NULL) + 
  guides(fill = guide_legend(title = "Rank", nrow = 1, reverse = TRUE)) +
  gg_theme
```
